"""Shared LaTeX-safe Jinja rendering and text sanitizers."""
import re
import unicodedata

import jinja2

_DIGITS = dict(zip('0123456789', ('Zero', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine')))
_ESCAPES = dict(zip('\\{}$&#%_^~', (
    r'\textbackslash{}', r'\{', r'\}', r'\$', r'\&', r'\#', r'\%',
    r'\_', r'\textasciicircum{}', r'\textasciitilde{}',
)))


def to_camel_case(value: str) -> str:
    """Return an ASCII letters-only TeX identifier; spell digits (score2 -> ScoreTwo)."""
    value = unicodedata.normalize('NFKD', str(value)).encode('ascii', 'ignore').decode()
    words = re.findall(r'[A-Za-z]+|[0-9]', value)
    result = ''.join(_DIGITS[w] if w.isdigit() else w[0].upper() + w[1:] for w in words)
    if not result:
        raise ValueError(f"Cannot form a TeX identifier from {value!r}")
    return result


def tex_escape(value) -> str:
    """Escape plain text exactly once, including TeX control characters."""
    return ''.join(_ESCAPES.get(c, c) for c in str(value))


def get_latex_env(template_dir: str | None = None) -> jinja2.Environment:
    env = jinja2.Environment(
        loader=jinja2.FileSystemLoader(template_dir) if template_dir else jinja2.BaseLoader(),
        block_start_string=r'\BLOCK{', block_end_string='}',
        variable_start_string=r'\VAR{', variable_end_string='}',
        comment_start_string=r'\#{', comment_end_string='}',
        autoescape=False, undefined=jinja2.StrictUndefined, keep_trailing_newline=True,
    )
    env.filters.update(to_camel_case=to_camel_case, tex_escape=tex_escape)
    return env


_VARIABLES = r"""% Machine generated by tuttireporting. Do not edit.
\BLOCK{for name, value in variables.items()}
\newcommand{\\VAR{name}}{\VAR{value}}
\BLOCK{endfor}
"""


def render_variables(variables: dict[str, str]) -> str:
    """Render validated macro names and already escaped values."""
    if any(not re.fullmatch(r'[A-Za-z]+', name) for name in variables):
        raise ValueError('TeX macro names must contain ASCII letters only')
    return get_latex_env().from_string(_VARIABLES).render(variables=variables)
